import Head from "next/head";
import axios from "axios";
import { useState } from "react";
import AddButton from "../components/AddButton";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import Add from "../components/Add";
import Footer from "../components/Footer";
import Featured from "../components/Featured";
import ProductList from "../components/ProductList";
export default function Home({ productList, admin }) {
  const [close, setClose] = useState(true);
  return (
    <div>
      <Head>
        <title>
          Delishhh - Real Food, Realistic Prices, Non For Profit Delivery...
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />

      {<AddButton setClose={setClose} />}
      <ProductList productList={productList} />
      {!close && <Add setClose={setClose} />}
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }
  const res = await axios.get(
    "https://master--delishhhapp.netlify.app/api/products"
  );

  return {
    props: {
      productList: res.data,
    },
  };
};
