import Head from "next/head";

import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Featured from "../components/Featured";
import ProductList from "../components/ProductList";
export default function Home() {
  return (
    <div>
      <Head>
        <title>
          Delishhh - Real Food, Realistic Prices, Non For Profit Delivery...
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <ProductList />
    </div>
  );
}
